
# Technique Thresholds
TOP_ELBOW_THRESHOLD = 120
TOP_ARM_FLEX_THRESHOLD = 150
TOP_ARM_ADD_THRESHOLD = 170
TOP_ARM_ROT_THRESHOLD = 160

BOTTOM_ELBOW_THRESHOLD = 80

LUMBAR_BENDING_THRESHOLD = 170
LUMBAR_EXTENSION_THRESHOLD = 235

# Score Thresholds

