
# Technique Thresholds
TOP_ELBOW_THRESHOLD = 120
TOP_ARM_FLEX_THRESHOLD = 50
TOP_ARM_ADD_THRESHOLD = 170
TOP_ARM_ROT_THRESHOLD = 160

BOTTOM_ELBOW_THRESHOLD = 80

LUMBAR_BENDING_THRESHOLD = 170
LUMBAR_EXTENSION_THRESHOLD = 235
HIP_FLEXION_THRESHOLD = 70

# Score Thresholds
TOP_ARM_GOOD_SCORE = 0.2
TOP_ARM_BAD_SCORE = 0.7

BOTTOM_ARM_GOOD_SCORE = 0.2
BOTTOM_ARM_BAD_SCORE = 0.7

POSTURE_GOOD_SCORE = 0.2
POSTURE_BAD_SCORE = 0.7

POSITIVE_ANGLE_SCORE = 0.2
